
import "../../public/assets/css/style.css";
import "./globals.css";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import Sidebar from "../../components/Sidebar";


export const metadata = {
  title: "Dynamic Render Demo All",
  description: "Generated by KMG",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body>
        <Header/>
        <Sidebar />
        <main id="main" className="main"> {children}</main>
        <Footer />
        </body>
    </html>
  );
}
